#!/usr/bin/env python

# Copyright Hash-LSH Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#########################################################################    ##
#
# Author: Anthony Hirales Ahuatzin, Fiona Kuang 
# Email : anthony.hirales@cetys.edu.mx fiona.kuang@cetys.edu.mx
#
#########################################################################    ##

import os
import pandas as pd


            
def load_inverted_index( ):
    colnames = ['key','val']
    inv_index = pd.read_csv( "psychosocial_cardiovascular_invindex.txt", encoding='utf8', sep=" ", names=colnames, header=None)
    inv_index = inv_index.set_index('val')
    return inv_index


def search(arr,inv_index):
    for i in arr:
        print(inv_index.loc[i, "key"])


inv_index = load_inverted_index()
#arreglo a buscar (vector)
arr = [1279, 4000, 6079, 1437, 3661, 5779, 3097, 3224, 5282]
search(arr,inv_index )
